name: 🐛 Bug Report
description: Report a problem or unexpected behavior
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please check the logs and provide as much context as possible.
  - type: input
    id: version
    attributes:
      label: solo-rs-pool version
      placeholder: e.g. v0.1.0
  - type: input
    id: rust-version
    attributes:
      label: Rust toolchain version
      placeholder: e.g. rustc 1.81.0
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the problem
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Include any runtime output or stratum/bitcoind RPC logs if available
      render: shell
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Start bitcoind (testnet/regtest)
        2. Run cargo run
        3. Connect miner X
        4. Observe Y
